### PR TITLE
Update information

### PR DESCRIPTION
**Pull request by Xee1**
Changelog:
- Moved ExAliquo to OldModTextures

- Reformatted and updated Readme, Todo and added a ModSupported file.

What do you guys think of these changes? @DZCreeper @Iclario @iMarbot @EddyHg80 
Preview:
https://github.com/Xee1/Faithful32-1.7.10/blob/master/MODSUPPORTED.md
https://github.com/Xee1/Faithful32-1.7.10/blob/master/README.md
https://github.com/Xee1/Faithful32-1.7.10/blob/master/TODO.md

### CODE REVIEW

**Comment by DZCreeper** [comment]
Some changes to README.md

Issues:

Have you found a bug or an outdated/broken texture that you want to let us know about? Open an issue.

Have you found a bug or an outdated/broken texture and you want to help to fix this? Read below!

Contributing:

Would you like to contribute to updating/adding textures to this pack? Simply follow these steps:

1) Fork this repository and clone on your Git client.

2) Make your changes in your fork and commit your changes to Github with your client.

3) Make a pull request on this repository, with a reasonable description of any changes made.

4) You have Done.

**Comment by Xee1** [comment]
Merge and feel free to edit everything you want @DZCreeper

**Comment by DZCreeper** [comment]
Change MODSUPPORT.md to indicate that some mods are partially supported, not that they could be partially supported.

Change TODO.md to remove the bottom 5 list of things. Also, seeing how you just did a massive cleanup, add whatever you feel is an appropriate project to the list. Also, remove this part:

'These are organized from most important to least:'

because that is no longer the case.

**Comment by DZCreeper** [comment]
Made 3 pull requests on your fork to fix the problems I indicated. Merge those and its ready to go.

**Comment by Xee1** [comment]
Thanks @DZCreeper , sorry for bad english!

**Comment by Iclario** [comment]
What is your first language @Xee1 ?

**Comment by Xee1** [comment]
Italian, from this year I'm focussing to learn english very well.

**Comment by Xee1** [comment]
@DZCreeper  I merged your commits

**Comment by Iclario** [comment]
Is it ready to merge ?

**Comment by Xee1** [comment]
I think yes

**Comment by EddyHg80** [comment]
Woa I'm italian too :D

**Pull request merged**
