### PR TITLE
Harvestcraft Part2, Dimensional Anchors, MODSUPPORT & TODO Update

### PR DESCRIPTION
**Pull request by steveowashere**
Did a bunch of work on Harvestcraft blocks almost all plant blocks are textured. Will continue with items eventually. The starfruit textures gave me some problems, would be nice if someone else could give it a try. 

Added support for Immibis Dimensional Anchors because it was one block that needed to be textured. 

Updated MODSUPPORT.md for Draconic Evolution, Dimensional Anchors, and Galacticraft Planets.

### CODE REVIEW

**Comment by Xen1290** [comment]
:+1:

**Comment by DZCreeper** [comment]
I don't have much time to look right now but the final stage of the crops could use some rounding. The papaya and peach for example doesn't look block-y but the edges are a little rough.

Don't worry too much about it, its high enough quality to merge but I will wait until tonight when I am at my desktop so I can edit them if I need.

**Comment by steveowashere** [comment]
Sounds good, make whatever changes you feel are needed.

**Comment by DZCreeper** [comment]
If you want to work on them now I can merge before tonight which is over 12 hours away. The work isn't a problem but my desktop is in pieces right now. Texture editing from a phone is... tricky.

**Comment by steveowashere** [comment]
Ah alright, no worries then. I'll take have another go at them. It's currently 7pm where i'm at, but I should be able to finish them tonight. 

I know about computers being in pieces my NAS box had harddrive and a PSU fail just last week.

**Comment by steveowashere** [comment]
Updated, hope it's an improvement.

**Comment by DZCreeper** [comment]
Definitely an improvement.

**Comment by StefanTT** [comment]
:+1:

**Pull request merged**
