### PR TITLE
Magical Crops 4.0 Update

### PR DESCRIPTION
**Pull request by Chinnchilla**
Added 4.0 textures to TODO. Moved old textures to OldModTextures just in
case. Renamed and copied usable textures to assets. Also do we animate ores if the ore is animated to begin with? Nothings really animated in vanilla.

### CODE REVIEW

**Comment by Evolution0** [comment]
Yes.. as far as I know this pack isn't about vanillafi'ing mods its about making 32x versions of textures in the style of its origin.

**Comment by Chinnchilla** [comment]
K in that case the overworld and nether ore need updated

**Comment by Chinnchilla** [comment]
Wait if its already 32x like some thaumcraft textures are do we leave it?

**Comment by Evolution0** [comment]
I would assume so, no need to remake them if they already meet the resolution requirement.

**Comment by DZCreeper** [comment]
If textures already match the 32x32 requirement we leave them alone, same if they are higher than that.

@StefanTT already did some Magical Crops 4.0 work in https://github.com/F32Organization/Faithful32-1.7.10/commit/d55b69f9825bc8a846a4062dc07687c1a12b8fab and https://github.com/F32Organization/Faithful32-1.7.10/commit/6a67d327a111715b157cf1cb9cdf322a44451f79. Do your pull request overwrite any of that? It doesn't appear to but I want to be sure.

**Comment by Chinnchilla** [comment]
No it doesn't overwrite any of his texture. It mainly just cleans up the assets folder and updates the TODO one so its easier. Im going to work on ores and blocks tonight.

**Comment by StefanTT** [comment]
I did not remove the old textures because 4.0 is still in beta and if there are mod packs that use the mod they probably still use the old version. I would do this cleanup later in the year and leave it as it is. I have not found colliding icons so it should not be much of a problem.

**Comment by Chinnchilla** [comment]
Ok I'll close this and rework it so the seeds are textured and it keeps all the old textures the remake the pull request when i finish the blocks and ores. The only name conflict I can find is the overworld and nether ore so should i go ahead and do those even though it would overwrite the older versions ores to the new ones?

**Pull request closed without merging**
