### PR TITLE
Terrafirmacraft tools and ingots

### PR DESCRIPTION
**Pull request by StefanTT**
+ terrafirmacraft tools and ingots
+ some terrafirmacraft ores
+ two ihl items

### CODE REVIEW

**Comment by Xen1290** [comment]
:+1:

**Comment by StefanTT** [comment]
Too bad that nobody with merge rights has time nowadays.

**Comment by Xen1290** [comment]
Yeah...

**Comment by DZCreeper** [comment]
Sorry about the prolonged absence, real life just caught up with me. Going to try and get back into texturing now that I have some free time.

**Comment by StefanTT** [comment]
I understand this. I have the problem too often for my taste.
Please tell me if I can be of any help.

**Pull request merged**
