### PR TITLE
Even more Tinkers Construct & some Simply Jetpacks

### PR DESCRIPTION
**Pull request by Zyx-2000**
Made TCon metal dusts, the remaining brownstone blocks, and the remaining slime-related blocks. Also did some things from Simply Jetpacks.

### CODE REVIEW

**Comment by DZCreeper** [comment]
brownstone_rough_road needs a little more gravel color. Should be pretty easy, add noise at 15 intensity, 100 color saturation, and 100 coverage.

graveyardsoil needs a bit more work, it looks better than the original but doesn't tile quite as well.

consecratedsoil has the same problem and the spots are a little darker than they should be.

brownstone_smooth_fancy looks like the lines have just a little too much much saturation. The rest of the block is fine.

Everything else looks good to me and the issues I noticed are fairly minor.

**Comment by Zyx-2000** [comment]
I completely forgot the fact that the soils should be tileable... will try to fix that as soon as I have time. I'll also see what I can do about the brownstones.

**Comment by Zyx-2000** [comment]
I have fixed the soils, and the smooth brownstone. I can't seem to get the rough brownstone right. Should I remove it?

**Comment by DZCreeper** [comment]
No, can take care of that really quickly. Thank you for fixing the other stuff.

**Pull request merged**
