### PR TITLE
ExtraTiC Part 2 of 3 & Chisel Update

### PR DESCRIPTION
**Pull request by steveowashere**
More progress on ExtraTiC. About 2/3 done. All textured created with a macro automation script. Manually hand checked to verify quality. 

Made progress on Ice, Ice Pillars and Pumpkins from Chisel

### CODE REVIEW

**Comment by Adaptivity** [comment]
:+1:

**Comment by Xen1290** [comment]
:+1:

**Comment by fewizz** [comment]
:+1:  :+1:   :+1:   :+1:   :+1:

**Comment by Iclario** [comment]
Could you, please, split your commits by mods next time, especially when there is so many files. Awesome work by the way :+1:

**Comment by steveowashere** [comment]
@Iclario Sorry I must be misunderstanding you, isn't that what I did for this time? I had 3 commits, one for ExtraTiC stuff, one for Chisel ice blocks, and one for Chisel pumpkins blocks.

**Comment by Iclario** [comment]
Oh sorry ! I'm on my phone and I just saw the long list of file. So, that's great, sorry

**Comment by steveowashere** [comment]
No worries :)

**Pull request merged**
