### PR TITLE
added files for PoorOres

### PR DESCRIPTION
**Pull request by Xexanos**

### CODE REVIEW

**Comment by Iclario** [comment]
I agree with @imarbot but I don't like the textures too, I don't know if this is the originals or yours...

**Comment by Xee1** [comment]
This is the current owner of PoorOres, https://github.com/Xexanos/PoorOres

**Comment by Xexanos** [comment]
The original textures are normal 16x16 textures, but since I made these for testing I thought I would share them so they can be included since upscaling the smaller ones can only go so far and does cause problems with some patterns.

**Comment by DZCreeper** [comment]
Liking the original textures is irrelevant, the goal is to maintain the same looks as the originals but at a higher resolution.

**Pull request merged**
