### PR TITLE
IC2 Classic Update

### PR DESCRIPTION
**Pull request by Xen1290**
Ported ic2 classic textures to ic2 Classic Speiger version, the old ic2 classic (immibis version) is no longer updated(last update: june). Some textures need to be done, because this IC2 Classic (Speiger Version) is more complete and add new things. In ic2 textures folder some textures have _old.png, because are incomplete, so if everyone would add the new textures, the old ones are done.

### CODE REVIEW

**Comment by steveowashere** [comment]
I can try to take a look at some of these sprite sheets soon. Should be able to port some stuff from ic2 Experimental to ic2 Classic like items and a few blocks. The rest will have to be handmade.

**Comment by DZCreeper** [comment]
Before using textures from IC2 experimental anything possible should be imported from:

https://github.com/F32Organization/Faithful32-1.4.7/tree/master/ic2/sprites

Those sprite sheets should contain a fair portion of all the textures needed because they are the textures from the original pre-experimental IC2.

**Comment by steveowashere** [comment]
Good call @DZCreeper. Almost everything needed is in the 1.4.7 ic2 repo. Just needs a little reorganizing. Should be pretty straight forward. I'll try to include it in my next commit.

**Comment by Xen1290** [comment]
In teory, already done @DZCreeper . These textures are from that repo.
@steveowashere before doing the commit, wait until this is merged, or you will have conflict files.

**Comment by steveowashere** [comment]
Will do. Probably won't have my next commit ready until Sunday anyway.

**Comment by DZCreeper** [comment]
@Xen1290 I understand now, this pull request moves support from IC2 Classic by immibis to IC2 Classic by speiger and also updates the TODO section for IC2 Classic.

I see the folders don't share names, so if you copy the files instead of moving them that would be great. We don't want to be pulling support for any users that haven't switched mod versions but do update their resource pack regularly.

**Comment by Xen1290** [comment]
@DZCreeper IC2 Classic (Immibis) is very bugged, nobody uses it. Also, Immibis version is bugged with resourcepack, only GUI support works. @Speiger can confirm this.

**Comment by Speiger** [comment]
@DZCreeper Immibis Texture Load system was a System that did searched for Textures in his Jar and that was it. I use a close system but made it for the ResourceSystem of MC compatible,
the reason that i changed the guiFolder name is simply that IC2 Classic and IC2 Exp can be supported both and have no Conflicts with Each other. (Which would happen then and that would be bad)
^^" Also i am already thinking that IC2 Classic (Immibis) is dead.

**Pull request merged**
