### PR TITLE
EnderIO and ElectroMagicalTools Update

### PR DESCRIPTION
**Pull request by MrVizzyTM**

### CODE REVIEW

**Comment by Adaptivity** [comment]
@DZCreeper I think it's fine to merge block and item textures for Ender IO beta. Especially, since tterrag released few public betas on curse. The betas relatively stable and fixed tons of bugs so I think people will update to them. And furthermore, I think nobody wants to make double-work: separated textures for stable and beta versions.
@MrVizzyTM keep in mind that gui textures should go here: https://github.com/F32Organization/Faithful32-1.7.10/tree/master/DevModTextures/enderio-2.3/textures/gui

**Comment by MrVizzyTM** [comment]
@Adaptivity yes. Thanks!

**Comment by steveowashere** [comment]
Excellent work! The sword textures look really nice. 

One question. Why are textures like blocks/capacitorBank.png being deleted? Has it changed in later versions? Maybe we should leave support in for people on older versions of the mod. Unless I misunderstood something.

**Comment by MrVizzyTM** [comment]
I add it in nex EnderIO commit!

**Comment by MrVizzyTM** [comment]
blocks/capacitorBank.png have vania 32x32

**Comment by steveowashere** [comment]
Ah okay, my mistake :P

**Comment by MrVizzyTM** [comment]
Can you merge it?

**Comment by MrVizzyTM** [comment]
@DZCreeper can you merge it?

**Comment by DZCreeper** [comment]
@MrVizzyTM, currently EnderIO is still technically in a beta phase so I would like to hold on textures for it until there is a release version. If you can separate those textures into a different pull request that would be appreciated.

**Comment by MrVizzyTM** [comment]
ok

**Pull request closed without merging**
