### PR TITLE
Ender IO: added buckets, capacitor, soul vessel, and most missing GUIs

### PR DESCRIPTION
**Pull request by StefanTT**

### CODE REVIEW

**Comment by Adaptivity** [comment]
Not sure if I correct but original capacitorBank.png(https://github.com/SleepyTrousers/EnderIO/blob/master/resources/assets/enderio/textures/gui/capacitorBank.png) different from your. Can you recheck it?

**Comment by StefanTT** [comment]
capacitorBank and enchanter both have leftover graphics on the right that never show up in game.  They are even not complete icons, only parts that were overpainted. If you have concerns I add them to the images, but for me they were of no use. Just tell me in case, I have no problem to add them :-)

With the gear colors you are right - I try to improve them.

**Comment by Adaptivity** [comment]
Well, if they're not displayed in-game it's make sense. Thanks for information.

**Comment by StefanTT** [comment]
You are always welcome, thanks for the feedback.

**Pull request merged**
