### PR TITLE
AE2, Magicalcrops, Buildcraft 7, Rotarycraft items, Harvestcraft. 

### LINKED ISSUE #488: Magical Crops: Core, Armory, and Decorative
Hi there! Is there any way that you could complete more of the textures for magical crops? I know the seeds are mostly done but none of the tools or armor or blocks are done. It would be greatly appreciated! Thanks!

### PR DESCRIPTION
**Pull request by steveowashere**
Small update this week. 

AE2: Finished off a few blocks from TODO

Magicalcrops: As requested added a few items. Blocks will be added next time. Closes #488 

Buildcraft 7: Started creating textures for new BC 7 machines

Rotarycraft: (finally) Started to update item sprite sheet.

Harvestcraft: Added random items.

### CODE REVIEW

**Comment by Xen1290** [comment]
Wow! :+1:

**Comment by steveowashere** [comment]
Thanks! 

I forgot to mention, I started a new repo for 'Faithful 32 variety'. Basically just added more variety for blocks with MCpatcher. Random grass sides, cobblestone, plants, ect. I feel these changes don't belong in the main faithful pack. If anyone wants to help out, take a look: https://github.com/steveowashere/Faithful32-MoreVariety-1.7.10

**Comment by TheVizzy** [comment]
+1 Good!

**Comment by DZCreeper** [comment]
"Small update"

You appear to have a slight problem with size calculation but in a good way. Excellent work as always.

**Pull request merged**
