### PR TITLE
ProjectRed updates

### PR DESCRIPTION
**Pull request by Wolf68k**
Removed textures no longer used or not really updated to 32
Added items\mechanical\crafting.png and extension.png
Updated TODO list

Side question: is there an IRC channel or an official forums or something to that affect. I have questions sometimes.

### CODE REVIEW

**Comment by steveowashere** [comment]
Textures look good! 

There is only the official forum post made by Vattic for the Faithful texture pack that I am aware of, and it's normally pretty dead over there. It would be handy to have from IRC or something for questions, because I have a few sometimes too.

**Comment by Wolf68k** [comment]
Well the issue I have is with the Projectred anode  and cathode. In the mod they look one way but in the F32 pack they are different. Maybe they changed in the mod since the F32 textures were made.
Either way, just thought it was odd is all.

Mod:
http://i.imgur.com/4PxzZtz.png
http://i.imgur.com/CgVppox.png

F32
http://i.imgur.com/D1gBxDJ.png
http://i.imgur.com/LTBTfso.png

**Comment by steveowashere** [comment]
Strange, they appear to just be flipped somehow. Must be a mistake from whoever made them for F32.  Probably doesn't make a huge difference since they are just items. But it's best to have them how the mod originally has them imo.  You can just flip them in Photoshop, I think there is feature called 'Flip Canvas Horizontally' if I remember correctly. Should be under the 'Image' tab. I would look but i'm on mobile.

**Comment by Wolf68k** [comment]
I actually did try that. Looked like crap and still off.
This is a quick horizontal flip but to get the T in the right direction I had to add a 90degree CCW
http://i.imgur.com/fSXtBVl.png

**Comment by steveowashere** [comment]
Oh yea, I suppose that would happen... well the only other way would be to redo those textures from the anode and cathode. I really don't think it's worth it to be honest.

**Comment by DZCreeper** [comment]
Sorry for the late update. I am fairly certain the textures are off because they were pulled from the old Redpower 2 support instead of made from scratch.

**Pull request merged**
