### PR TITLE
GregTech

### PR DESCRIPTION
**Pull request by Xee1**
- For first, rename folder
- Other files to move
- Most of basicmachines textures, and TODO. Yes, 300 files for one folder
in blocks folder...
- The textures on TODO with -tofix in the name is to say that it must be
correct some particulars
- They seems so many textures missing, but they are actually very few,
many are the same, but in different folders
- Fixed wrong names
- Other textures, many of this commit are void, name only.
- Most of materialicons in blocks folder ported!
- Finished materialicons!
- Added TODO(a Lot of files, but most of  are the same! Also it missing
very few textures!)
- Finished import iconsets and TODO!
- Removed old textures
- Other things
- 80% Gui ported/done
- Items ported
- TODO
- Other

And also:
-Removed Botany TODO folder.
-Renamed OutdatedTextures folder.

### CODE REVIEW

**Comment by EddyHg80** [comment]
9229 files changed... you are crazy :D

**Comment by Xee1** [comment]
Yes, because greg with his mod counts as 100 mods!

**Comment by fewizz** [comment]
O_o

**Comment by DZCreeper** [comment]
You hear that? Its my internet connection and the Github servers slowly dying as they alter over 9000 files.

**Comment by Xee1** [comment]
Most of ores,(missing only small ore) few machines and items(plate,rod,ingot,gems,etc) and I'm finishing the gui.

There are a lot of files, but most are the same!
(For example 10 folders where in each one there are the same texture.)
@DZCreeper 
Edit:I've also noticed that there is in IC2 forum a tread with Faithful 64x64 for gregtech, it support a lot of things. (http://forum.industrial-craft.net/index.php?page=Thread&threadID=11244 if you need this)

**Comment by Xee1** [comment]
Anyone know greg and his mod. It's adds 1023288 items/blog every release

**Comment by DZCreeper** [comment]
That Faithful 64x64 Gregtech support pack looks good but only use it in a pinch. Rather avoid getting into a tussle about permissions and downscaling textures rarely works well for individual sprites.

**Comment by Xee1** [comment]
I've thought the same thing!

**Pull request merged**
