### PR TITLE
Terrafirmacraft blocks

### PR DESCRIPTION
**Pull request by StefanTT**
+ Added all clay, sand, dirt, farmland blocks
+ Updated shale rock
+ Added quern (device)

### CODE REVIEW

**Comment by Xen1290** [comment]
👍🏻

**Comment by StefanTT** [comment]
I added the farmland for all soil types since the initial push.

**Comment by StefanTT** [comment]
Oh my, the request is still not merged?
Sorry, I did not check and now the project red fix was pushed here too.

**Comment by Xen1290** [comment]
👍🏻 for merging

**Comment by StefanTT** [comment]
@DZCreeper please merge

**Comment by StefanTT** [comment]
Sigh.

**Comment by Xen1290** [comment]
@DZCreeper is possible to have the ability to merge comits? It's ugly leave the P.R. Here without merging in the repository.

**Comment by Iclario** [comment]
He seems to be a little busy these days

**Comment by StefanTT** [comment]
No problem, thank you for merging! :+1:

**Comment by Iclario** [comment]
It's a really good work by the way

**Pull request merged**
