### PR TITLE
Create wand_cap_manasteel.png.mcmeta

### PR DESCRIPTION
**Pull request by Unrepentant-Atheist**

### CODE REVIEW

**Comment by StefanTT** [comment]
Is there a reason why you create an extra pull request for every file?

**Comment by Xee1** [comment]
Please, make only one pull request. One is sufficient. @Unrepentant-Atheist

**Comment by Iclario** [comment]
Thanks for the email spamming

**Comment by Unrepentant-Atheist** [comment]
I fail at GitHub...still learning how to do it. How do I create more than 1 files and submit pull request?

**Comment by DZCreeper** [comment]
Fork, clone to your computer, make changes, put them into commits, send pull request.

Iclario, next time please don't merge pull requests like this. Nothing wrong with them, it just clutters stuff up.

**Comment by fewizz** [comment]
Unrepentant-Atheist,  http://git-scm.com/videos

**Comment by Iclario** [comment]
Right @DZCreeper, sorry

**Pull request merged**
