### PR TITLE
Thermal Foundation items

### PR DESCRIPTION
**Pull request by Zyx-2000**
Added Thermal Foundation buckets, and missing materials and metal blocks.

### CODE REVIEW

**Comment by Evolution0** [comment]
Your awesome :D

**Comment by DZCreeper** [comment]
Excellent work! I appear to have bad timing though, because I just finished redoing the Thermal Foundation fluids and the matching buckets myself: https://github.com/F32Organization/Faithful32-1.7.10/commit/2283ecf26a3b1ac37b224dbc012a98857b74d06c

You will need to remove those before I can merge the pull request. Another minor issue is the coloring of the Signalum gear and dust/blend is slightly off. If you wouldn't mind fixing that, I would really appreciate it. If you don't want to or can't get the coloring quite right, let me know and I will merge this anyways and touch it up myself.

**Comment by Zyx-2000** [comment]
I've fixed those issues now. Signalum was difficult to get right, because it has both yellow and red in it, unlike most other metals which only have one primary colour.

**Comment by Xee1** [comment]
Very good work, Awesome!

**Pull request merged**
