### PR TITLE
Fix BC

### PR DESCRIPTION
**Pull request by TheVizzy**
@Evolution0 thats ok?

### CODE REVIEW

**Comment by Evolution0** [comment]
I already fixed it in my PR, and nah those are still BC6 based (black/yellow/black/yellow). In BC7 its yellow/black/yellow/black.

**Comment by TheVizzy** [comment]
Man.. i know!

**Comment by TheVizzy** [comment]
idk how close this PR

**Comment by EddyHg80** [comment]
https://youtu.be/UePtoxDhJSw :D

**Comment by TheVizzy** [comment]
hahah!

**Comment by TheVizzy** [comment]
Black and yellow!

**Comment by TheVizzy** [comment]
https://github.com/TheVizzy/Faithful32-1.7.10/commit/86a6e0b82c34dfbe1c1a7e99ca2b84455262b3a1

**Comment by Evolution0** [comment]
Yeah the linked commit is correct but I've already done all the markers in my PR along with a bunch of other stuff.

**Comment by DZCreeper** [comment]
Going to close this and merge the other PR. Also going to look into getting a small IRC server or some other type of message board setup. Using Github for communication is sub-par

.If someone has suggestions for a lightweight self-hosted messaging system, let me know.

**Pull request closed without merging**
