### PR TITLE
Added 8 pipes and 4 pipe braces

### PR DESCRIPTION
**Pull request by GamerM**
This is my first ever git pull request so i'm still pretty new to this (also learn git in a 4 days which is pretty good). Anyways added 8 pipes and 4 braces. These are base off the additional pipes design so it can be consistent.  What do you guys think? Hope you like it.

Before:

After:

### CODE REVIEW

**Comment by TheVizzy** [comment]
Nice

**Comment by Iclario** [comment]
That's a great work, thank you

**Comment by GamerM** [comment]
Woohoo!

**Comment by Iclario** [comment]
I know that feeling when your first pull request is accepted ;)

**Pull request merged**
