### PR TITLE
Carpenters blocks: doors and bed designs.

### PR DESCRIPTION
**Pull request by StefanTT**
This is the same as my pull request #199, with corrected commits.

### CODE REVIEW

**Comment by DZCreeper** [comment]
I don't personally use this mod, I rarely play at actually. I will forgo my usual side by side comparison if you wouldn't mind taking one or two screenshots of the blocks this covers. Or if someone that does use the mod can comment on the quality.

**Comment by StefanTT** [comment]
It's the glass / mesh in the doors:
minecraft 1 7 10_032
minecraft 1 7 10_031

And the beds:
minecraft 1 7 10_033
logs_034

**Comment by DZCreeper** [comment]
If its not too much trouble I think the screen door would look better with the mesh being closer together. While its good to remain faithful to the original textures, I think making it slightly more realistic in this case is called for, the originals are just limited by what I think is the 10x26 size of the original/

**Comment by StefanTT** [comment]
The door uses the same texture twice, so I can only change the mesh in horizontal direction - or make it even smaller than this.

Now it would look like this:
minecraft 1 7 10_035

**Comment by Xee1** [comment]
I use that mod, and, for me, he did a very good work!

**Pull request merged**
