### PR TITLE
FM Update!

### PR DESCRIPTION
**Pull request by TheVizzy**

### CODE REVIEW

**Comment by TheVizzy** [comment]
Commit this!

**Comment by Iclario** [comment]
What about a please ? Sorry but your pull request can not be merge automatically, there might be conflict with other commits. Please, update your fork and try again.

**Comment by TheVizzy** [comment]
can you merge it pls

**Comment by StefanTT** [comment]
There are still merge conflicts. I think you need to update your (forked) repository and rebase your change to fix the conflicts.

**Comment by TheVizzy** [comment]
hmm. I update fork. Wats i need make!

**Comment by TheVizzy** [comment]
And. How delete pull request

**Comment by StefanTT** [comment]
You can close your pull request and open a new one after fixing your repo, if this is what you mean.
I think it can be fixed by fixing your commits too, but unfortunately I am no expert on these things.

**Comment by Iclario** [comment]
I close it for you, pease, do an other pell request

**Comment by Evolution0** [comment]
git remote add upstream https://github.com/F32Organization/Faithful32-1.7.10
git fetch upstream
git rebase upstream/master

That should get you up to date without losing your changes, then you can do a new PR.

**Pull request closed without merging**
