### PR TITLE
MachineMuse Modular Powersuits TODO folder update.

### PR DESCRIPTION
**Pull request by TheVizzy**

### CODE REVIEW

**Comment by steveowashere** [comment]
That was quick! Didn't it just get released for 1.7.10 24 hours ago?

Looks good to me though.

**Comment by Xen1290** [comment]
It's released from about a year

**Comment by steveowashere** [comment]
Oh okay, I must be mistaken then. I just saw on reddit that a mod called Module Powersuits was released on curse yesterday. I don't really keep up with mods very well as I should. 

http://minecraft.curseforge.com/mc-mods/235442-modular-powersuits

**Comment by Xen1290** [comment]
Ah, you mean released on curse, the mod Itself is out from about a year on jenkins :)

**Comment by steveowashere** [comment]
Ahh okay, that explains it!
Like I said, I really don't keep up with mods like I should. :P

**Pull request merged**
