### PR TITLE
Nuclearcraft, Redstone Armory, IC2 Classic, Harvestcraft, Thermal Foundation, Chromaticraft, Geostrata  

### LINKED ISSUE #475: (Botania) Chiseled Livingrock Brick
Chiseled Livingrock Brick looks nearly identical to regular Livingrock Brick. Was this a mistake somewhere?

http://imgur.com/a/DOX32 (Imgur album comparing the two blocks with and without the resource pack).

### PR DESCRIPTION
**Pull request by steveowashere**
Nuclearcraft: Updated for latest version. 

Redstone Armory: Added support, No animated textures yet. 

IC2 Classic: Imported sprites and guis from 1.4.7 repo. Reworked as needed. 

Harvestcraft: Added a few items. 

Thermal Foundations: Added Basalz & Biltz models

Chromaticraft: Added a bunch of blocks.

Geostrata: Added different variants of stone. 

Fix #475 

Closed #475

### CODE REVIEW

**Comment by Xen1290** [comment]
:+1::+1::+1: Very good !

**Comment by DZCreeper** [comment]
NuclearCraft looks good, fairly simple textures.

Same with Redstone Armory.

IC2 Classic looks as good as I remember it. You can use the textures from block_electric.png and block_generator.png to finish the compact solar textures. Appears to be a new column, advanced machine types? The final 8 items in item_0.png are all the same and just a recolor of the OV and OD scanner.

HarvestCraft looks great, I hate texturing food so double thanks there!

Not even sure when Thermal Foundation added new mobs but those look okay.

I don't use ChromatiCraft or Geostrata much so someone else will have to chime in for those.

**Comment by steveowashere** [comment]
Will try to make those changed to IC2 classic stuff, if you don't mind holding off to merge for 24h or so.

**Comment by Speiger** [comment]
The Reinforced Reactor is a Steam Reator,
the second Vents at the bottom are steam vents, and the scanners are a upgraded scanners (had no texture so copies)
But we have the Ranges Scanner, Bigranged scanners and OreValueDensetyScanners (low/med/high/adjustable)
I hope that info helps^^

**Comment by steveowashere** [comment]
@Speiger Any idea what you would like the scanners to look like? If i'm making them for this pack I mine as well also make them for you as well (if that's okay).

There are 8 scanner sprites, so from left to right maybe you can tell me what each one is suppose to be and what you have in mind and i'll try to make something work for that :)

**Comment by Speiger** [comment]
Em i have no wishes^^" Suprise me for now.
Order is: 
-Ranged OD,
-Ranged OV,
-BigRanged OD,
-BigRanged OV,
-Low OVD,
-Med OVD,
-High OVD,
-Adj OVD
^^" Also loads these textures like that.

**Comment by steveowashere** [comment]
Okay, here's what I came up with. Nothing fancy but should be okay to tell the items apart. I went with the gray color instead of blue, to my eyes it looks better. Hope they're okay :P 

16x16: 
scanner16



32X32:

scanner32

**Comment by DZCreeper** [comment]
I like both the originals and the Faithful versions of those scanners. Going to merge and if Speiger decides to use something different they can be changed later.

**Comment by steveowashere** [comment]
@Speiger If you want to use my 16x16 textures for your mod you can download it from here: 

scanner16

**Comment by Speiger** [comment]
Hmmm the Range of the Orevalue scanners are having not a big range... (6 blocks that is lower then a any other upgraded scanner)
i like the textures but there is for me to much gray... (Its i do also not like always the copy of the same scanner but i had no other option now)
A better indicactor for the OreValue check should be there, because the scanners now show only the range their doing which is by the way not right. (I changed the text above which tells the sorting)

**Comment by Speiger** [comment]
Just an info. IC2 Classic gains soon a Converter Block Sprite sheet which will be new (and some other stuff) i will give to you guys a Sheet before the release comes out^^

**Comment by steveowashere** [comment]
Sounds good! Thanks for the heads up :)

**Comment by Speiger** [comment]
No Problem. There will be maybe a couple more new additions too. Not sure what will join yet.

**Comment by Speiger** [comment]
Textures are finish for the update. Here you have access for the Update which will be released in a couple days. Sunday proberly^^"
Link: http://www.mediafire.com/download/r71yz419njlm5c4

**Comment by Speiger** [comment]
@steveowashere

**Pull request merged**
