### PR TITLE
NuclearCraft Fix

### PR DESCRIPTION
**Pull request by steveowashere**
I forgot to set the correct name of the NuclearCraft assets folder. My bad, only realized this months after making the textures and finally playing Minecraft again.

### CODE REVIEW

**Comment by Xen1290** [comment]
Welcome back!

**Comment by Iclario** [comment]
Thanks ;)

**Comment by steveowashere** [comment]
@Xen1290 Thanks, but I don't know how much I'll be able to work on Faithful-32 textures these days. I have a Master's Thesis to write. But after that i'll hopefully get back to making some textures :)

**Comment by Iclario** [comment]
Haha, I feel so dumb

**Pull request merged**
