### PR TITLE
RFTools 1.7.10 Final Retexture

### PR DESCRIPTION
**Pull request by Evolution0**
Quick update and first part of RFTools final re-texture for Faithful32 1.7.10

Do not merge until I am finished, PR is for feedback/comments as I work on it.

Let me know what you think, specifically the front "grille" of machines, not sure if I should leave it square or do like I did with the original re-texture I did.

So yeah.. I'm kinda back?

### CODE REVIEW

**Comment by Evolution0** [comment]
Lack of updates over the past 2 days is due to an annoying cold, should be back at it soon.

**Comment by Xen1290** [comment]
Good for me except for
machineBlockProtector
machineBlockProtectorOn
They're low quality compared with the currents in the F32 pack.

**Comment by Xen1290** [comment]
And... welcome back!

**Comment by Evolution0** [comment]
Hm yeah I think I did better on the shield the first time, I'll just swap out the shield image for the old one.

**Comment by Evolution0** [comment]
So quick question, how do you guys feel about adjusting the machineRelay(D,U,N,E,S,W) texture to match the rest of the textures since the mod author did a recolor? (Relay is still the old blue) and any other textures that are still blue for that matter.

Seems to be one of the textures that is still blue and 16x16 by default rather than the newer 32x32 and grey.

I could either base it off of what it is (What we normally do) or remake it in the newer style (for consistency)

**Comment by Xen1290** [comment]
For me match with originals.

**Comment by Evolution0** [comment]
Yeah that seems to be the way to go, even though newer versions of rftools (after 4.23) have a grey relay since those using the 1.7.10 Faithful resource pack are most likely using the last 1.7.10 version it makes sense.

**Comment by DZCreeper** [comment]
Are we good to merge here? Real life has left me with very little time for a texturing hobby but I will try to get F32 Modded back on its feet over the next 2-3 days. The main thing will be done switching the site to 1.7.10 and 1.10.2 instead of 1.7.10 and 1.6.4.

**Comment by Evolution0** [comment]
Yeah you can merge this, I'm trying to get back into Minecraft but obligations to other gaming communities etc are sucking up my time.

**Pull request merged**
