### PR TITLE
Nevermine

### PR DESCRIPTION
**Pull request by fewizz**

### CODE REVIEW

**Comment by Iclario** [comment]
Pretty good work but there is a problem, the color of the ingots is not redirected, could you please fix it. Thanks

**Comment by fewizz** [comment]
ok

**Comment by fewizz** [comment]
why? all respected. or say me name of problematic ingot.

**Comment by Iclario** [comment]
sans titre

The colors of the elecanium are different from the original.

**Comment by fewizz** [comment]
thanks

**Comment by Iclario** [comment]
I can make a pull request to fix it, if you want

**Comment by fewizz** [comment]
yes

**Comment by fewizz** [comment]
now? 
image

**Pull request merged**
