### PR TITLE
fix ingots

### PR DESCRIPTION
**Pull request by fewizz**

### CODE REVIEW

**Comment by DZCreeper** [comment]
If you could adjust the line on the Baronyte and Emberstone that would be great. It creates a bit more contrast then is intended in those particular ingots.

**Comment by Iclario** [comment]
What do you mean with "adjust the line" ?

The color of this line ?

sans titre

**Comment by DZCreeper** [comment]
No, the white line. Vanilla iron and gold ingots have that line but it makes sense because light reflecting off them would be close to white. Ingots like these still need the line but should be colored closer to what reflected light would look like.

**Comment by Iclario** [comment]
Fixed

98194e7e0b8a8d894bed0fa45ddd831865f1e212

**Pull request closed without merging**
