### PR TITLE
Railcraft tools and enderio items

### PR DESCRIPTION
**Pull request by StefanTT**

### CODE REVIEW

**Comment by Adaptivity** [comment]
Are you sure about binder composite? Your 32x32 texture a bit different from new original: https://github.com/F32Organization/Faithful32-1.7.10/blob/master/TODO/enderio/textures/items/binderComposite.png

**Comment by Iclario** [comment]
I totaly agree with @adaptivity, could you, please make it in the faithful dust style

**Comment by StefanTT** [comment]
Am 2015-03-22 um 12:48 schrieb Farès Chati:
>
> I totaly agree with @adaptivity <https://github.com/adaptivity>, could 
> you, please make it in the faithful dust style
>
Ok I'll rework it, thanks for the feedback.

**Comment by Adaptivity** [comment]
Looks good for me. Nice work. For the next time: use textures from TODO folder or directly from Ender IO repository because almost all textures changed and they will be available in the next Ender IO version.

**Comment by StefanTT** [comment]
Ok I'll do so - this is the better way, of course.

**Comment by Adaptivity** [comment]
@Iclario can you pull it if everything ok for you?

**Comment by Iclario** [comment]
Oh ! I didn't see the second commit, sorry

**Pull request merged**
