### PR TITLE
Ender IO: powders and filter upgrades

### PR DESCRIPTION
**Pull request by StefanTT**
Also aligned ic2 coal dust by one pixel to match the coal dusts of the other mods.
Receipts look much nicer in NEI now that the coal dust does not "jump" anymore.

### CODE REVIEW

**Comment by steveowashere** [comment]
Looks nice. Was just about to take care of the EIO Powders but you beat me to it.

**Comment by StefanTT** [comment]
Oh sorry

**Comment by steveowashere** [comment]
Oh no worries, No need to apologize, just was saw that they needed to be done and was planning on doing them next week sometime. 

We could really use a Google doc (or something) so people can mark down what they would like to work on. So we don't end up working over each other... Just a thought. .. Don't know if it's a good one or not.

**Comment by DZCreeper** [comment]
Made a Google Doc, link is in TODO.md. Send me an email with the address that you wanted added to the edit list.

**Pull request merged**
