### PR TITLE
FIX for immersive engineering voltmeter

### PR DESCRIPTION
**Pull request by StefanTT**
This fixes issue #521

### CODE REVIEW

**Comment by StefanTT** [comment]
Please merge, it's blocking my master branch.

**Comment by Xen1290** [comment]
@DZCreeper

**Comment by xMrVizzy** [comment]
Okay okay!

**Comment by xMrVizzy** [comment]
Guys i don't love now IC2 xD Author renamed all texture names and change folders in 1.9 xD

**Pull request merged**
