### PR TITLE
Minor SteamCraft update.

### PR DESCRIPTION
**Pull request by TheVizzy**

### CODE REVIEW

**Comment by DZCreeper** [comment]
If you could give slightly more descriptive commit names, that would be great. Something like 'Minor SteamCraft update' would be enough. Just so people on the website have some idea of what has changed.

Also, I don't really use any of the mods you do work for. I just don't play very much anymore unless its for texturing or to help new server owners out. If someone that does could let me know how the quality of this work is, that would be great.

**Comment by MrVizzyTM** [comment]
ok! And commit this update)))

**Comment by EddyHg80** [comment]
Could you please give a link to the mod? I checked Steamcraft 2 (which, by the way, has the same folder name) but I don't see the items you made.

**Comment by Xee1** [comment]
The mod is Flaxbeard's Steam Power @EddyHg80

**Comment by EddyHg80** [comment]
Ok fine, merging it!

**Pull request merged**
