### PR TITLE
Et Futurum support

### PR DESCRIPTION
**Pull request by Adaptivity**
[Et Futurum](http://minecraft.curseforge.com/mc-mods/230114-et-futurum)
Textures were taken from official Faithful32 pack and from [Faithful Snapshots repository](https://github.com/TheVizzy/FaithfulSnapshots).
Credits for textures from snapshots goes to @TheVizzy So, let's wait for him to confirm that he is ok to include his textures.

### CODE REVIEW

**Comment by Adaptivity** [comment]
@TheVizzy ?

**Comment by TheVizzy** [comment]
Hi?

**Comment by TheVizzy** [comment]
Yes you can include my textures.

**Comment by TheVizzy** [comment]
Хоть кто-то оценил мою работу над снапшотами) :+1:

**Comment by TheVizzy** [comment]
Но! @Adaptivity обнови пожалуйста новые текстуры которые я сегодня выложил!

**Comment by Adaptivity** [comment]
Thanks, I'll update them right now.

**Comment by Xen1290** [comment]
Very good 1.9 textures! Good work @TheVizzy @Adaptivity

**Comment by Adaptivity** [comment]
Updated. Should be ready to merge.

**Comment by fewizz** [comment]
TheVizzy, просто никто не пользуется снапшотами.

**Comment by TheVizzy** [comment]
:dancer:

**Pull request merged**
