### PR TITLE
Forbidden magic

### PR DESCRIPTION
**Pull request by fewizz**

### CODE REVIEW

**Comment by DZCreeper** [comment]
You have this marked 1/10, would you like me to merge now or wait? I don't use Forbidden Magic myself but everything looks fine.

**Comment by fewizz** [comment]
wait.

**Comment by fewizz** [comment]
DONE!

**Comment by Iclario** [comment]
Beautiful work, well done !

**Comment by StefanTT** [comment]
Yep, very nice :+1:

**Comment by fewizz** [comment]
thanks =)

**Comment by Xee1** [comment]
Very good!

**Pull request merged**
