### PR TITLE
Magical crops: items, mostly essences

### PR DESCRIPTION
**Pull request by StefanTT**
I removed the infusion stones, as the original icons are already 32x32.

### CODE REVIEW

**Comment by Iclario** [comment]
It seems that the cropessence_peridot texture is still in 16x16, I think it's an error, please fix it :)

**Comment by Iclario** [comment]
This is a very good work anyway

**Comment by Adaptivity** [comment]
Nice work :smile: You've done so many textures. Keep it up!

**Comment by StefanTT** [comment]
Oh ... I messed with my repository yesterday, sorry. I will fix it.

**Pull request closed without merging**
