### PR TITLE
Blood Magic, Thermal Foundation. Misc.

### PR DESCRIPTION
**Pull request by Evolution0**
Started recoloring the Thermal Foundation materials (our colors are outdated). Main reason I'm putting it in the pull request is so you guys can take a look at it and compare it to TFs current vanilla textures, I believe I'm getting them as close as possible but want a second opinion.

Ignore the "Merge branch 'master'" bit, something wonky about my repo but it doesn't effect it any. I probably need to clean my workspace up, delete my clone, reclone my repo and set this repo as upstream. If the commit message gets annoying just let me know.

### CODE REVIEW

**Comment by StefanTT** [comment]
Looking good to me :+1:
The bronze dust is not 100% perfect, if you would urge me to be picky. But it's nothing that troubles me.

**Comment by DZCreeper** [comment]
If you redo cinnabar, the Induction Smelter GUI will need a small update.

**Comment by Evolution0** [comment]
@StefanTT:  Hm.. I thought so too, is it the sharpness of the highlight? (really obvious line in the center?)

@DZCreeper: Thermal Expansion right? Yeah I'll keep that in mind, id forgotten that it had that split texture icon thing.

**Comment by Evolution0** [comment]
Closed, deleted my now broken fork, and recloned properly.

Tried fixing it but it turned out to be more trouble than it was worth so started over.

Don't worry I made sure to back my work up before doing so.

**Comment by StefanTT** [comment]
I don't know if it would have helped, but have a look (read: google) for "git push -f" to fix the commits of your private repository. The next time you need to drop a change. It feels a bit strange to use it but it did the trick for me.

**Comment by Evolution0** [comment]
Yeah I made a mistake early on and cloned the main repo and not my fork so for a while I was just making changes and pushing to mine manually so of course when it came time to pull.. you see what happened above.

should be fine now though.

**Pull request closed without merging**
