### PR TITLE
magianaturalis blocks

### PR DESCRIPTION
**Pull request by TheVizzy**

### CODE REVIEW

**Comment by StefanTT** [comment]
Nice update :+1:

Maybe you could have more meaningful commit messages in the future, instead of only "Update". It makes managing the commits much easier.

**Comment by TheVizzy** [comment]
Idk how name that update :)

**Comment by StefanTT** [comment]
How about "magianaturalis blocks" ?
I try to name it with what it obviously contains.

**Comment by Evolution0** [comment]
Just "Update" is a bad habit.

Personally I tend to at least state the name of the mod then a small comment about what in particular was changed during commit and if I feel more info should be provided I usually drop a few lines in the PR comment.

Makes keeping track of changes easier.

**Comment by Iclario** [comment]
Beautiful work ! :+1:

**Pull request merged**
