### PR TITLE
Aether 2 Update

### PR DESCRIPTION
**Pull request by TheVizzy**

### CODE REVIEW

**Comment by Xen1290** [comment]
:+1:

**Comment by steveowashere** [comment]
Looks good to me. +1 for merging.

**Comment by DZCreeper** [comment]
@TheVizzy Do you know how to do commit squashing? Not a big deal but it would be tidier if you could convert the 4 commits into 1 because they are all the same subject.

If you want to learn the easy way using the Git command line, check the second answer on this stackoverflow.com thread.

http://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git

**Comment by TheVizzy** [comment]
i use GutHub Client. Sorry.

**Pull request merged**
