### PR TITLE
Advanced Solar Panels

### PR DESCRIPTION
**Pull request by DocNeO**
Advanced Solar Panels

Armor
After
advancedsolarhelmet advancedSolarHelmet (New)
Before
advancedsolarhelmet
After
hybridsolarhelmet hybridSolarHelmet (New)
Before
hybridsolarhelmet
After
ultimatesolarhelmet ultimateSolarHelmet (New)
Before
ultimatesolarhelmet

Blocks
After
hsp_bottom hsp_bottom
Before
hsp_bottom
After
hsp_side hsp_side
Before
hsp_side
After
qsp_side qsp_side
Before
qsp_side
After
qsp_side_copy qsp_side_copy
Before
qsp_side_copy

Gui
After
guiadvancedsolarpanel GUIAdvancedSolarPanel (New)
Before
guiadvancedsolarpanel
After
guimoleculartransformer_nei guiMolecularTransformer_nei
Before
guimoleculartransformer_nei
After
guimoleculartransformernew guiMolecularTransformerNew 
Before
guimoleculartransformernew
After
guiquantumgenerator GUIQuantumGenerator (New)
Before
guiquantumgenerator

Items
After
advsolarhelmet AdvSolarHelmet (New)
Before
advsolarhelmet
After
enrichedsunnarium EnrichedSunnarium (New)
Before
enrichedsunnarium
After
hybridsolarhelmet HybridSolarHelmet
Before
hybridsolarhelmet
After
quantumcore QuantumCore
Before
quantumcore
After
sunnarium Sunnarium (New)
Before
sunnarium
After
ultimatesolarhelmet UltimateSolarHelmet (New)
Before
ultimatesolarhelmet

Models
After
texturemoleculartransformer  textureMolecularTransformer
Before
texturemoleculartransformer

### CODE REVIEW

**Comment by Greenphlem** [comment]
Looks great to me!

**Comment by DocNeO** [comment]
thank

**Comment by DZCreeper** [comment]
Files need to be changed, not just  Today or tomorrow I can merge this manually. Reason it takes longer is because with just the attachments it doesn't save the folder name or give me an easy view of old and new versions.

**Comment by DocNeO** [comment]
I added examples of old textures and changed the texture on Sunnariums more like vanilla

**Comment by Xen1290** [comment]
Welcome back @EddyHg80 !

**Pull request closed without merging**
