### PR TITLE
Biomes O' Plenty Textures

### PR DESCRIPTION
**Pull request by steveowashere**
Took care of a few textures in Biomes O' Plenty TODO folder. Hopefully should be able to do a few more soon.

About the Flesh texture (\blocks\flesh.png), The original was too hard to directly scale up from 16x16. So I did a little re-working. If anyone doesn't like it/doesn't fit with the faithful style. I'll create a commit to remove it and it won't be added, no problem. But I think it looks good enough to be in the pack. 

The texture in question: 
Original:
flesh

My version: 
flesh

Screenshots: 

Edit: Oops I included the version of the  bluemilk.png block, and DZCreeper has already authored one. I can create a pull request to remove that if wanted. Whichever version looks better.

### CODE REVIEW

**Comment by DZCreeper** [comment]
Looks good to me. Just going to wait another day to see if anyone has a different opinion.

**Comment by steveowashere** [comment]
:+1: Sounds good.

**Comment by Iclario** [comment]
Looks beautiful for me

**Comment by Xen1290** [comment]
Good for me!

**Pull request merged**
