### PR TITLE
Ztones items

### PR DESCRIPTION
**Pull request by StefanTT**

### CODE REVIEW

**Comment by Iclario** [comment]
There is a missing pixel in the hunger item and the mini charcoal looks too dark beside the original

**Comment by StefanTT** [comment]
I'll fix the missing pixel but are you sure about the too dark charcoal item?
In gimp, my charcoal and the original (from ztones version 2.2.1) look like this:

bildschirmfoto vom 2015-06-28 12 10 52

Is my version really darker?

**Comment by Iclario** [comment]
I'm on mobile, so I cannot send you a screenshot but the deleted mini charcoal in TODO looks really clearer that the one you sent

**Comment by Iclario** [comment]
Are you sure this is charcoal and not coal ?

**Comment by StefanTT** [comment]
Very sure. Here is another screenshot with all 3 items in one image:
my charcoal, the original charcoal, the original coal.

bildschirmfoto vom 2015-06-28 12 27 43

You are right, the deleted image looks lighter in the web view. I now compared it by downloading the image from the f32 todo's directory directly from github. Its the same as in the screenshots. Don't ask me why it looks that different.

**Comment by Iclario** [comment]
It's okay, maybe a problem from github, I guess

**Comment by StefanTT** [comment]
Ok.  You could merge then, I already fixed the missing pixel by modifying my commit.

**Comment by Iclario** [comment]
Oh, I was waiting for an other commit. Nice work, by the way

**Comment by StefanTT** [comment]
No problem, thanks for reviewing!

**Comment by Iclario** [comment]
You're welcome

**Pull request merged**
