### PR TITLE
Meta-data stripping

### PR DESCRIPTION
**Pull request by Unrepentant-Atheist**
Stripped every picture of useless meta-data. Saved about https://i.imgur.com/PadsdDO.png

### CODE REVIEW

**Comment by steveowashere** [comment]
Wow nice work, 70mb, that's a pretty good savings. 

But wouldn't it be better for the server that builds that packs for F32.me to do the meta-data stripping? (I think) Linux has a native command for it. I don't know anything of the backend of the site though. But for the purposes of github, does it really matter saving space?

**Comment by Evolution0** [comment]
@steveowashere Yes, yes it would.

We have had issues before where stripping metadata caused MCs engine to interpret textures differently and cause issues like the colors being wrong or too bright (especially greyscale textures) therefor it is better to do this server side during build time as it maintains the integrity of the originals.

Have you tested to make sure everything looks correct @Unrepentant-Atheist ?

**Comment by Unrepentant-Atheist** [comment]
I have. See no problem. Though I don#t use every mod. But a lot of them.

**Comment by steveowashere** [comment]
I'm confused here. You said you tested all 36,765 textures, but don't use all the mods for them?

**Pull request closed without merging**
