### PR TITLE
Random Additions - Awesome Mod, Update textures to 1.7.10

### PR DESCRIPTION
**Pull request by TheVizzy**
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1288963-randomadditions-alpha-v0-10-updated-adding-a-new

### CODE REVIEW

**Comment by Xee1** [comment]
Random addition! Good mod.

**Comment by Mineyourwayhome** [comment]
hi can u do textures for draconic evolution im not sure how to create a new thing to ask but this is the link
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2093099-draconic-evolution-1-0-1rc4

**Comment by DZCreeper** [comment]
@Mineyourwayhome I haven't personally used Draconic Evolution but I recall hearing people say it already uses 64x64 textures or higher. If that is indeed the case its not much of a priority, Faithful 32 is focused on increasing the quality of textures below 32x32, anything above is likely to be ignored or simply downscaled. I will take a look at it in the near future though and perhaps do some downscaling.

**Comment by Xee1** [comment]
Yeah, Draconic evolution uses 64x or highter textures, except for Armor.

**Comment by Mineyourwayhome** [comment]
thank you for letting me know

**Pull request merged**
