### PR TITLE
Witchery

### PR DESCRIPTION
**Pull request by Oftheball**
Most Books of Witchery

### CODE REVIEW

**Comment by DZCreeper** [comment]
I don't personally use Witchery so if someone else can check the books that would be great.

**Comment by steveowashere** [comment]
Tested in game, and they look good to me. 
+1 for merging. 

Nice work @Oftheball

**Comment by Xen1290** [comment]
+1

**Comment by Oftheball** [comment]
Bonjour ! Hello ! 
First of all, thanks you all ! 
Next, i am working on other textures for Witchery. I'll try to be more faithful as possible but it's quite difficult sometimes to see what 2 or 4 pixels can be... so don't hesitate to say you're not agree with my "suppositions". (And you can criticize my english too...)

**Comment by steveowashere** [comment]
@Oftheball Just do what you think looks best, and we will tell you if there is a problem :)

**Pull request merged**
