### PR TITLE
Nei, IC2

### PR DESCRIPTION
**Pull request by fewizz**

### CODE REVIEW

**Comment by fewizz** [comment]
oops

**Comment by DZCreeper** [comment]
What exactly did you change? I know the NEI gui's were already done.

**Comment by fewizz** [comment]
Oh yes, sorry about nei...  -_-    . I will change it tomorrow.

 I added, and changed some missed textures (crops, and etc.) from TODO/ic2/textures to asset/ic2/textures, and deleted two unused folders in TODO/ic2/textures. This normal? :smile:

**Comment by DZCreeper** [comment]
Alright, I will merge this tomorrow once you fix the NEI stuff. Thanks for catching the IC2 stuff, the TODO folder isn't supposed to have finished textures in it but I guess some slipped through.

**Comment by Xee1** [comment]
Very good work! By the way IC2 TODO folder isn't updated,(it missing GT textures. Yes, GT add textures in ic2 folder) I will fix all TODO and folder files, I've my TODO list.
For Nei textures I think is the only GUI missing https://github.com/F32Organization/Faithful32-1.7.10/blob/master/TODO/nei/textures/nei_sprites.png and Parteon icon.
Sorry for english, I'm on mobile.

**Pull request closed without merging**
