### PR TITLE
Chisel, Extra Utilities, TiC

### PR DESCRIPTION
**Pull request by Artemmr**
**Chisel**
New GUI updated
Presents updated
Glass CTM updated
Renamed chisel to chisel_iron
Updated chisel_diamond
Some techical blocks updated
TODO updated for 2.3.7.34
**Tinkers Construct**
TiC heart bars updated
TiC inventory tab updated
**Extra Utilities**
GUI updated
Wings and items updated
Connected Textures updated

### CODE REVIEW

**Comment by Xee1** [comment]
Good work!

**Comment by DZCreeper** [comment]
Merge conflict on:

OldModTextures/chisel/textures/items/brush.png: needs merge
OldModTextures/chisel/textures/items/iceshard.png: needs merge
assets/chisel/textures/items/brush.png: needs merge
assets/chisel/textures/items/chisel_diamond.png: needs merge
assets/chisel/textures/items/iceshard.png: needs merge
assets/chisel/textures/items/unused/brush.png: needs merge
assets/chisel/textures/items/unused/iceshard.png: needs merge

Please fix those conflicts or rebase the pull request. Information on how to do so: https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

**Comment by Adaptivity** [comment]
I guess this because I proposed PR with some Chisel textures. They shouldn't be pulled at all because they are already in.

**Comment by Artemmr** [comment]
I made rebase, but not sure if right.

**Pull request merged**
