### PR TITLE
Progress on Big Reactors & Botania

### PR DESCRIPTION
**Pull request by steveowashere**
Finished off all the blocks from the Big Reactor TODO

Fixed typo in MODSUPPORT.md 

Started on updating Botania. Worked on biome blocks mostly and a few flowers/ random blocks. 

Need feedback on biome blocks, not sure if they are up to standards. I tiled the original  16x16 to make 32x32 and then used the clone tool to blend areas that look repeated. The patterns on the blocks are smaller but this was the result: 

These are the originals

Added fix for Issue #448 
Nickel ore from Immersive Engineering needed a little adjustment. See linked issue for screenshots.

### CODE REVIEW

**Comment by Xen1290** [comment]
Good for me, great work!

**Comment by steveowashere** [comment]
Cool, thanks @Xen1290 :)

**Comment by DZCreeper** [comment]
The tiled 16x16 looks fine in my opinion but doesn't suit the Faithful style.

The rest looks fine to me.

**Comment by steveowashere** [comment]
Alright, no problem. I'll revert the changes to those blocks.

**Comment by steveowashere** [comment]
Made another attempt at the biome stones from Botania: 



Much improved this time imo. I also worked on a few more flowers and alter models. 

Also took care of a few chisel textures, namely: Brick, Snakestone, Temple, Temply Mossy and Stonebrick 2.

**Comment by DZCreeper** [comment]
I only looked at two types of the stone but there are too many areas that appear 16x16.

Its definitely an improvement but areas that are 2x2 or more of the same color stand out and need reshaping or shading.

**Comment by TheVizzy** [comment]
First attempt better)

**Comment by fewizz** [comment]
no, second.

**Comment by TheVizzy** [comment]
no, first :) Second very smoothed!

**Comment by steveowashere** [comment]
Or maybe the third attempt is the best? 


I took @DZCreeper 's advice and blended some of the 2x2 areas.Hope everyone is pleased with this version :)

**Comment by DZCreeper** [comment]
Excellent work, looks perfect to me asides from some a very minor visual problem with tiling on numbers 5 and 11. Can't avoid that on some blocks though.

**Pull request merged**
