### PR TITLE
Chisel work & small fixes to AE2

### PR DESCRIPTION
**Pull request by Artemmr**
**Chisel**
GUI updated
Fully updated folders: *marble, marbleslab, marblepillarslab, laboratory, concrete, present, limestone, paper*
Partially updated folders: *stonebrick, factory*
**AE2**
MAC texture fixed
Quantum ring lights fix
Inscriber GUI fix (3 pixels deleted)

### CODE REVIEW

**Comment by Iclario** [comment]
Nice work :)

**Comment by Iclario** [comment]
Is it all your work ?

**Comment by Artemmr** [comment]
Yes, except *present* they from vanilla pack

**Comment by Iclario** [comment]
OK, your work is pretty good.

**Pull request merged**
