### PR TITLE
ExtraTic Part 3 of 3, Botania, Iguana Tinkers Tweaks, NEI Sprite Cleanup

### PR DESCRIPTION
**Pull request by steveowashere**
Sorry about huge number of file changes. 
ExtraTiC = 98% of everything is now textured. Only missing items are the items from 'fun_stuff' and Galacticraft. Which can't be automated because the textures are unique. Will included these in next commit. As usual, all textures created with macro automation script, and checked 3 times by hand.

Botania: All plants now textured! Plus a bunch of other blocks

Iguana Tinkers Tweaks: Buckets and Mob heads

NEI: Cleaned up Moon and rain sprite. They had transparent pixels around them, that looked bad. 
See Screenshot:

afternei
 
Update: Added support for Uncrafting Table Mod:http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1290409-uncrafting-table-mod-works-for-all-items-even-from

### CODE REVIEW

**Comment by Adaptivity** [comment]
:+1: You are also might want to check some fun stuff, ingot and GC textures which were made by me. They are already in the repository but you might want to change them since my texturing skills are very simple :)

**Comment by steveowashere** [comment]
I can take a look. 
Noob Github question: Is there a way to view all files one person has added to a repo?

**Comment by Adaptivity** [comment]
Something like this https://github.com/F32Organization/Faithful32-1.7.10/commits/master?author=steveowashere?

**Comment by steveowashere** [comment]
Perfect, just what I needed :)

**Comment by DZCreeper** [comment]
nei_sprites might need a total redo. The originals don't really match any existing textures in the game and the current ones that you fixed up are loose interpretations, especially the magnet and trashcan.

http://f32.me/nei_sprites.png is the original.

**Comment by steveowashere** [comment]
Might as well just update them all together then. Shouldn't take too long.

**Comment by steveowashere** [comment]
@DZCreeper Is this any better? 

updatednei

**Comment by fewizz** [comment]
my old nei sprites :cry: ... Looks good. :+1:

**Comment by Xen1290** [comment]
Very good!

**Comment by steveowashere** [comment]
Sorry @fewizz :(

Thanks @Xen1290

**Comment by steveowashere** [comment]
Sorry @DZCreeper, I didn't make the new pull request for the sprites in my before you merged. I'll do that now.

**Pull request merged**
