### PR TITLE
BC Update!

### PR DESCRIPTION
**Pull request by TheVizzy**

### CODE REVIEW

**Comment by Evolution0** [comment]
There is a reason I didn't copy those textures over, for example the new laser beams are semi-transparent and not noisy at all, those old BC6 ones are completely opaque a very noisy.

A lot (if not all) of the new BC7 textures are less saturated, have less contrast, and are very "smooth".

**Comment by TheVizzy** [comment]
ok i fix it'

**Comment by Evolution0** [comment]
From the looks of it you would be better of closing the PR, reverting your commits locally, then fixing it (redoing the textures rather than copying), committing, and making a new PR.

**Comment by TheVizzy** [comment]
How close PR?

**Comment by Iclario** [comment]
Like this

**Comment by TheVizzy** [comment]
thx

**Comment by TheVizzy** [comment]
))

**Comment by Iclario** [comment]
There is a "close pull request" button on the bottom

**Pull request closed without merging**
