### PR TITLE
Immersive Engineering

### PR DESCRIPTION
**Pull request by steveowashere**
Took a little 'creative liberty' with the ore since they do not follow the conventional ore styles. 

Original: 
al_org
lead_org

Modified: 

lead_mod
al_mod

Should be able to finish up the rest of the mod by this weekend.

### CODE REVIEW

**Comment by Xen1290** [comment]
Very good ! For the ores, I Think DZCreeper should decide.

**Comment by DZCreeper** [comment]
For the aluminum that single colored pixel should go and maybe drop that 3 pixel area a bit.

For the lead maybe make the 2 pixel area a bit larger and add a similar area directly in the center.

Just suggestions, take whatever liberties you want to make them look good. They are great already, I just think evening out the color distribution a little more would make them look better.

**Comment by steveowashere** [comment]
Thanks @Xen1290 !

If you don't mind waiting to merge, i'll try those suggestions tomorrow @DZCreeper to see if I can get them to look even better.

**Comment by steveowashere** [comment]
Update, I think they look much better. Thanks for the tips. 

al_mod
lead_mod

**Comment by Greenphlem** [comment]
Ores look much better +1 to merging!

**Pull request merged**
